[build]
  base = ""
  publish = "client/dist"
  command = "npm run build"
[context.production.environment]
  # Ensure the environment variable is set here
  VITE_API_URL = "diy-project-hub-production.up.railway.app"